@extends('layouts.admin')
@section('title','Media')
@section('topbar','Media Library')
@section('content')
<div class="heading"><div><h1>Media Library</h1><p>Upload gambar homepage dan creative asset Temoe Tumbuh.</p></div></div>
<form class="card card-pad" method="post" enctype="multipart/form-data" action="{{ route('admin.media.store') }}" style="margin-bottom:18px">@csrf<div class="grid" style="grid-template-columns:2fr 2fr auto;align-items:end"><div class="field"><label>File gambar</label><input class="input" type="file" name="file" accept="image/*" required></div><div class="field"><label>Alt text</label><input class="input" name="alt_text" placeholder="Contoh: ruang bermain Temoe Tumbuh"></div><button class="btn btn-primary">Upload</button></div><div class="help" style="margin-top:10px">JPG, PNG, WebP, GIF, SVG. Maksimal 8 MB.</div></form>
<div class="grid" style="grid-template-columns:repeat(auto-fill,minmax(190px,1fr))">@forelse($media as $item)<div class="card" style="overflow:hidden"><div style="aspect-ratio:4/3;background:#eceae3;overflow:hidden"><img src="{{ asset('storage/'.$item->path) }}" alt="{{ $item->alt_text }}" style="width:100%;height:100%;object-fit:cover"></div><div class="card-pad" style="padding:14px"><strong style="font-size:13px;display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">{{ $item->original_name }}</strong><div class="help" style="margin:6px 0;word-break:break-all">/storage/{{ $item->path }}</div><form method="post" action="{{ route('admin.media.destroy',$item) }}" onsubmit="return confirm('Hapus gambar ini?')">@csrf @method('DELETE')<button class="btn btn-danger" style="padding:7px 9px">Hapus</button></form></div></div>@empty<div class="card empty">Belum ada media.</div>@endforelse</div>
@if($media->hasPages())<div class="actions" style="margin-top:18px">@if(!$media->onFirstPage())<a class="btn btn-outline" href="{{ $media->previousPageUrl() }}">← Sebelumnya</a>@endif<span class="help">Halaman {{ $media->currentPage() }} / {{ $media->lastPage() }}</span>@if($media->hasMorePages())<a class="btn btn-outline" href="{{ $media->nextPageUrl() }}">Berikutnya →</a>@endif</div>@endif
@endsection
