@extends('layouts.admin')
@section('title','Homepage CMS')
@section('topbar','Homepage CMS')
@section('content')
<div class="heading"><div><h1>Homepage</h1><p>Edit section, copy, CTA, dan gambar halaman pemasaran tanpa mengubah source code.</p></div><a class="btn btn-outline" target="_blank" href="{{ route('home') }}">Preview Website ↗</a></div>
<div class="grid grid-2" style="align-items:start"><div class="stack">
@forelse($sections as $section)
<form class="card card-pad" method="post" enctype="multipart/form-data" action="{{ route('admin.cms.update',$section) }}">@csrf @method('PUT')<div class="actions" style="justify-content:space-between"><div><strong>{{ $section->section_key }}</strong><div class="help">Urutan {{ $section->sort_order }}</div></div><label class="help"><input type="checkbox" name="is_active" value="1" @checked($section->is_active)> Aktif</label></div>
@if($section->image_path)<div style="margin-top:14px;border-radius:14px;overflow:hidden;max-height:220px;background:#eee"><img src="{{ str_starts_with($section->image_path,'http') ? $section->image_path : asset(ltrim($section->image_path,'/')) }}" alt="" style="width:100%;height:220px;object-fit:cover"></div>@endif
<div class="grid grid-2" style="margin-top:16px"><div class="field"><label>Judul</label><input class="input" name="title" value="{{ $section->title }}"></div><div class="field"><label>Subjudul</label><input class="input" name="subtitle" value="{{ $section->subtitle }}"></div></div><div class="field" style="margin-top:12px"><label>Konten</label><textarea class="textarea" name="content">{{ $section->content }}</textarea></div><div class="grid grid-2" style="margin-top:12px"><div class="field"><label>Upload gambar baru</label><input class="input" type="file" name="image" accept="image/*"><div class="help">Jika diisi, gambar lama pada section akan diganti.</div></div><div class="field"><label>Atau Image path / URL</label><input class="input" name="image_path" value="{{ $section->image_path }}" placeholder="/storage/... atau https://..."></div><div class="field"><label>CTA Label</label><input class="input" name="cta_label" value="{{ $section->cta_label }}"></div><div class="field"><label>CTA URL</label><input class="input" name="cta_url" value="{{ $section->cta_url }}"></div><div class="field"><label>Urutan</label><input class="input" type="number" name="sort_order" value="{{ $section->sort_order }}"></div></div><div class="actions" style="margin-top:15px"><button class="btn btn-primary">Simpan</button></div></form>
<form method="post" action="{{ route('admin.cms.destroy',$section) }}" onsubmit="return confirm('Hapus section ini?')">@csrf @method('DELETE')<button class="btn btn-danger">Hapus {{ $section->section_key }}</button></form>
@empty<div class="card empty">Belum ada section. Tambahkan section pertama di panel kanan.</div>@endforelse
</div>
<form class="card card-pad" method="post" enctype="multipart/form-data" action="{{ route('admin.cms.store') }}">@csrf<h3 class="section-title">Tambah Section</h3><div class="stack"><div class="field"><label>Section Key</label><input class="input" name="section_key" required placeholder="hero, benefits, pricing, faq..."><div class="help">Gunakan identifier unik.</div></div><div class="field"><label>Judul</label><input class="input" name="title"></div><div class="field"><label>Subjudul</label><input class="input" name="subtitle"></div><div class="field"><label>Konten</label><textarea class="textarea" name="content"></textarea></div><div class="field"><label>Upload gambar</label><input class="input" type="file" name="image" accept="image/*"></div><div class="field"><label>Atau Image path / URL</label><input class="input" name="image_path"></div><div class="grid grid-2"><div class="field"><label>CTA Label</label><input class="input" name="cta_label"></div><div class="field"><label>CTA URL</label><input class="input" name="cta_url"></div></div><div class="field"><label>Urutan</label><input class="input" type="number" name="sort_order" value="100"></div><label class="help"><input type="checkbox" name="is_active" value="1" checked> Tampilkan section</label><button class="btn btn-primary">Tambah Section</button></div></form></div>
@endsection
