@extends('layouts.admin')
@section('title','Leads')
@section('topbar','Leads')
@section('content')
<div class="heading"><div><h1>Leads</h1><p>Kelola calon orang tua dari formulir minat dan campaign acquisition.</p></div><div class="actions"><a class="btn btn-outline" href="{{ route('admin.leads.export') }}">Export CSV</a></div></div>
<div class="card card-pad" style="margin-bottom:16px"><form method="get" class="grid" style="grid-template-columns:2fr 1fr 1fr auto;align-items:end"><div class="field"><label>Cari</label><input class="input" name="q" value="{{ request('q') }}" placeholder="Nama, WhatsApp, email, kota..."></div><div class="field"><label>Status</label><select class="select" name="status"><option value="">Semua status</option>@foreach(['new'=>'New','contacted'=>'Contacted','qualified'=>'Qualified','high_intent'=>'High Intent','reserved'=>'Reserved','lost'=>'Lost'] as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select></div><div class="field"><label>Source</label><select class="select" name="source"><option value="">Semua source</option><option value="direct" @selected(request('source')==='direct')>Direct</option>@foreach($sources as $source)<option value="{{ $source }}" @selected(request('source')===$source)>{{ $source }}</option>@endforeach</select></div><button class="btn btn-primary">Filter</button></form></div>
<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Lead</th><th>Anak</th><th>Area</th><th>Budget</th><th>Source / Campaign</th><th>Status</th><th>Masuk</th></tr></thead><tbody>@forelse($leads as $lead)<tr><td><a href="{{ route('admin.leads.show',$lead) }}"><strong>{{ $lead->parent_name }}</strong></a><div class="help">{{ $lead->whatsapp }}</div></td><td>{{ $lead->child_name ?: '—' }}@if($lead->child_age !== null)<div class="help">{{ $lead->child_age }} tahun</div>@endif</td><td>{{ $lead->city ?: '—' }}<div class="help">{{ $lead->district }}</div></td><td>{{ $lead->budget_range ?: '—' }}@if($lead->reservation_interest)<div class="help">✓ Minat reservasi</div>@endif</td><td>{{ $lead->utm_source ?: 'direct' }}<div class="help">{{ $lead->utm_campaign ?: '—' }}</div></td><td><span class="badge badge-{{ $lead->status }}">{{ str_replace('_',' ',strtoupper($lead->status)) }}</span></td><td>{{ $lead->created_at->format('d M Y') }}<div class="help">{{ $lead->created_at->format('H:i') }}</div></td></tr>@empty<tr><td colspan="7" class="empty">Belum ada lead yang cocok dengan filter.</td></tr>@endforelse</tbody></table></div></div>
@if($leads->hasPages())<div style="margin-top:16px" class="actions">@if($leads->onFirstPage())<span class="btn btn-outline muted">← Sebelumnya</span>@else<a class="btn btn-outline" href="{{ $leads->previousPageUrl() }}">← Sebelumnya</a>@endif<span class="help">Halaman {{ $leads->currentPage() }} / {{ $leads->lastPage() }}</span>@if($leads->hasMorePages())<a class="btn btn-outline" href="{{ $leads->nextPageUrl() }}">Berikutnya →</a>@else<span class="btn btn-outline muted">Berikutnya →</span>@endif</div>@endif
@endsection
