@extends('layouts.admin')
@section('title',$lead->parent_name)
@section('topbar','Lead Detail')
@section('content')
<div class="heading"><div><div class="help"><a href="{{ route('admin.leads.index') }}">← Kembali ke Leads</a></div><h1 style="margin-top:6px">{{ $lead->parent_name }}</h1><p>{{ $lead->whatsapp }} · {{ $lead->email ?: 'Email belum diisi' }}</p></div><div class="actions"><a class="btn btn-soft" target="_blank" href="{{ $lead->whatsappUrl() }}">WhatsApp</a><span class="badge badge-{{ $lead->status }}">{{ str_replace('_',' ',strtoupper($lead->status)) }}</span></div></div>
<div class="grid grid-2">
<div class="stack">
    <div class="card card-pad"><h3 class="section-title">Profil Kebutuhan</h3><div class="grid grid-2"><div><div class="help">Nama anak</div><strong>{{ $lead->child_name ?: '—' }}</strong></div><div><div class="help">Usia anak</div><strong>{{ $lead->child_age !== null ? $lead->child_age.' tahun' : '—' }}</strong></div><div><div class="help">Kota</div><strong>{{ $lead->city ?: '—' }}</strong></div><div><div class="help">Kecamatan / area</div><strong>{{ $lead->district ?: '—' }}</strong></div><div><div class="help">Lokasi pilihan</div><strong>{{ $lead->preferred_location ?: '—' }}</strong></div><div><div class="help">Jadwal</div><strong>{{ $lead->preferred_schedule ?: '—' }}</strong></div><div><div class="help">Target mulai</div><strong>{{ $lead->preferred_start_date?->format('d M Y') ?: '—' }}</strong></div><div><div class="help">Budget</div><strong>{{ $lead->budget_range ?: '—' }}</strong></div></div><div style="margin-top:18px"><div class="help">Minat reservation / priority slot</div><strong>{{ $lead->reservation_interest ? 'Ya' : 'Belum' }}</strong></div></div>
    @if($lead->custom_fields)<div class="card card-pad"><h3 class="section-title">Jawaban Tambahan</h3><div class="grid grid-2">@foreach($lead->custom_fields as $key=>$value)<div><div class="help">{{ str_replace('_',' ',ucwords($key,'_')) }}</div><strong>{{ is_array($value) ? implode(', ',$value) : ($value ?: '—') }}</strong></div>@endforeach</div></div>@endif
    <div class="card card-pad"><h3 class="section-title">Attribution</h3><div class="grid grid-2"><div><div class="help">Source</div><strong>{{ $lead->utm_source ?: 'direct' }}</strong></div><div><div class="help">Medium</div><strong>{{ $lead->utm_medium ?: '—' }}</strong></div><div><div class="help">Campaign</div><strong>{{ $lead->utm_campaign ?: '—' }}</strong></div><div><div class="help">Content / Creative</div><strong>{{ $lead->utm_content ?: '—' }}</strong></div><div><div class="help">FBCLID</div><span class="help" style="word-break:break-all">{{ $lead->fbclid ?: '—' }}</span></div><div><div class="help">GCLID</div><span class="help" style="word-break:break-all">{{ $lead->gclid ?: '—' }}</span></div></div><div style="margin-top:14px"><div class="help">Landing Page</div><span class="help" style="word-break:break-all">{{ $lead->landing_page ?: '—' }}</span></div></div>
</div>
<div class="stack">
    <form class="card card-pad" method="post" action="{{ route('admin.leads.update',$lead) }}">@csrf @method('PUT')<h3 class="section-title">Follow-up & Qualification</h3><div class="field"><label>Status Lead</label><select class="select" name="status">@foreach(['new'=>'New','contacted'=>'Contacted','qualified'=>'Qualified','high_intent'=>'High Intent','reserved'=>'Reserved','lost'=>'Lost'] as $value=>$label)<option value="{{ $value }}" @selected($lead->status===$value)>{{ $label }}</option>@endforeach</select></div><div class="field" style="margin-top:14px"><label>Catatan follow-up</label><textarea class="textarea" name="notes" placeholder="Contoh: Sudah dihubungi via WhatsApp, butuh daycare mulai November...">{{ old('notes',$lead->notes) }}</textarea></div><button style="margin-top:14px" class="btn btn-primary">Simpan Perubahan</button></form>
    <div class="card card-pad"><h3 class="section-title">Lifecycle</h3><div class="kpi-list"><div class="kpi-row"><span>Lead masuk</span><strong>{{ $lead->created_at->format('d M Y H:i') }}</strong></div><div class="kpi-row"><span>Dihubungi</span><strong>{{ $lead->contacted_at?->format('d M Y H:i') ?: '—' }}</strong></div><div class="kpi-row"><span>Qualified</span><strong>{{ $lead->qualified_at?->format('d M Y H:i') ?: '—' }}</strong></div><div class="kpi-row"><span>Reserved</span><strong>{{ $lead->reserved_at?->format('d M Y H:i') ?: '—' }}</strong></div></div></div>
</div>
</div>
@endsection
