@extends('layouts.admin')
@section('title','Form Minat')
@section('topbar','Form Builder')
@section('content')
<div class="heading"><div><h1>Form Minat</h1><p>Atur pertanyaan market validation. Field baru otomatis disimpan sebagai data tambahan pada lead.</p></div><a class="btn btn-outline" target="_blank" href="{{ route('interest.create') }}">Preview Form ↗</a></div>
<div class="grid grid-2" style="align-items:start">
<div class="stack">
@forelse($fields as $field)
<form class="card card-pad" method="post" action="{{ route('admin.form-fields.update',$field) }}">@csrf @method('PUT')<div class="actions" style="justify-content:space-between"><div><strong>{{ $field->label }}</strong><div class="help">{{ $field->field_key }} · {{ $field->type }}</div></div><div class="actions"><label class="help"><input type="checkbox" name="is_required" value="1" @checked($field->is_required)> Wajib</label><label class="help"><input type="checkbox" name="is_active" value="1" @checked($field->is_active)> Aktif</label></div></div><div class="grid grid-2" style="margin-top:14px"><div class="field"><label>Label</label><input class="input" name="label" value="{{ $field->label }}" required></div><div class="field"><label>Tipe</label><select class="select" name="type">@foreach(['text','email','tel','number','date','select','radio','checkbox','textarea','hidden'] as $type)<option @selected($field->type===$type)>{{ $type }}</option>@endforeach</select></div><div class="field"><label>Placeholder</label><input class="input" name="placeholder" value="{{ $field->placeholder }}"></div><div class="field"><label>Urutan</label><input class="input" type="number" name="sort_order" value="{{ $field->sort_order }}"></div></div><div class="field" style="margin-top:12px"><label>Help text</label><input class="input" name="help_text" value="{{ $field->help_text }}"></div><div class="field" style="margin-top:12px"><label>Options (satu pilihan per baris)</label><textarea class="textarea" name="options_text">{{ $field->options ? implode("\n",$field->options) : '' }}</textarea></div><button style="margin-top:14px" class="btn btn-primary">Simpan Field</button></form>
<form method="post" action="{{ route('admin.form-fields.destroy',$field) }}" onsubmit="return confirm('Hapus field ini? Jawaban historis di leads tidak ikut terhapus.')">@csrf @method('DELETE')<button class="btn btn-danger">Hapus {{ $field->label }}</button></form>
@empty<div class="card empty">Belum ada field dinamis. Field inti masih tetap tampil di form.</div>@endforelse
</div>
<form class="card card-pad" method="post" action="{{ route('admin.form-fields.store') }}">@csrf<h3 class="section-title">Tambah Pertanyaan</h3><div class="stack"><div class="field"><label>Field Key</label><input class="input" name="field_key" required pattern="[a-z0-9_]+" placeholder="work_arrangement"><div class="help">Unik, huruf kecil/angka/underscore.</div></div><div class="field"><label>Label pertanyaan</label><input class="input" name="label" required placeholder="Bagaimana pola kerja orang tua?"></div><div class="field"><label>Tipe jawaban</label><select class="select" name="type">@foreach(['text','email','tel','number','date','select','radio','checkbox','textarea'] as $type)<option>{{ $type }}</option>@endforeach</select></div><div class="field"><label>Placeholder</label><input class="input" name="placeholder"></div><div class="field"><label>Help text</label><input class="input" name="help_text"></div><div class="field"><label>Options</label><textarea class="textarea" name="options_text" placeholder="WFO\nHybrid\nWFH"></textarea></div><div class="field"><label>Urutan</label><input class="input" type="number" name="sort_order" value="100"></div><div class="actions"><label class="help"><input type="checkbox" name="is_required" value="1"> Wajib</label><label class="help"><input type="checkbox" name="is_active" value="1" checked> Aktif</label></div><button class="btn btn-primary">Tambah Pertanyaan</button></div></form>
</div>
@endsection
